var assert=require('assert'), data={}, handlers={}, sent=[], failKey=null, failWrite=0;
global.localStorage={get length(){return Object.keys(data).length;},key:function(i){return Object.keys(data)[i]||null;},getItem:function(k){return data[k]===undefined?null:data[k];},setItem:function(k,v){if(k===failKey||(--failWrite===0))throw Error('injected');data[k]=v;}};
global.Pebble={addEventListener:function(n,f){handlers[n]=f;},sendAppMessage:function(p,ok){sent.push(p);if(ok)ok();}};
var sync=require('../src/pkjs/index.js');
var logs=[], originalLog=console.log; console.log=function(m){logs.push(String(m));};
var fs=require('fs'); var a=JSON.parse(fs.readFileSync('tests/fixtures/sync_a.json','utf8')); var b=JSON.parse(fs.readFileSync('tests/fixtures/sync_b.json','utf8'));
handlers.appmessage({payload:{message:JSON.stringify(a)}}); assert.strictEqual(sent.pop().ack,7); assert.strictEqual(sync.scanHistory().records['7'].id,7);
handlers.appmessage({payload:{message:fs.readFileSync('tests/fixtures/sync_b.json','utf8')}}); assert.strictEqual(sent.pop().ack,4294967295); assert.strictEqual(sync.scanHistory().records['4294967295'].w,1);
handlers.appmessage({payload:{message:JSON.stringify(a)}}); assert.strictEqual(sent.pop().ack,7);
var conflict=Object.assign({},a,{t:124}); sent.length=0; handlers.appmessage({payload:{message:JSON.stringify(conflict)}}); assert.strictEqual(sent.length,0);
handlers.appmessage({payload:{message:'bad'}}); assert.notStrictEqual(sent.pop().ack,7);
data.historyIndex='{bad'; var orphan=JSON.stringify({schemaVersion:1,records:[Object.assign({},a,{id:8})]}); data['historyChunk:0002']=orphan; assert(sync.store(Object.assign({},a,{id:8}))); assert.strictEqual(data['historyChunk:0002'],orphan);
failKey='historyChunk:0003'; sent.length=0; var indexBefore=data.historyIndex; handlers.appmessage({payload:{message:JSON.stringify(Object.assign({},a,{id:9}))}}); assert.strictEqual(sent.length,0); assert.strictEqual(data.historyIndex,indexBefore); failKey=null;
failWrite=1; assert(!sync.store(Object.assign({},a,{id:10}))); assert.strictEqual(data['historyChunk:0003'],undefined); failWrite=0;
failWrite=2; assert(!sync.store(Object.assign({},a,{id:10}))); failWrite=0; assert(sync.store(Object.assign({},a,{id:10})));
var corrupt='not-json'; data['historyChunk:0099']=corrupt; var beforeCorrupt=data['historyChunk:0099']; assert(sync.store(Object.assign({},a,{id:11}))); assert.strictEqual(data['historyChunk:0099'],beforeCorrupt);
['v','e','r'].forEach(function(k){var bad=Object.assign({},a); if(k==='v')bad.v=2; if(k==='e')bad.e=[0,3,4]; if(k==='r')bad.r=Array(14).fill(5); sent.length=0; handlers.appmessage({payload:{message:JSON.stringify(bad)}}); assert(sent.length===0||sent.pop().ack!==bad.id);});
var beforeConflictIndex=data.historyIndex, beforeConflictChunk=data['historyChunk:0001']; sent.length=0; handlers.appmessage({payload:{message:JSON.stringify(Object.assign({},a,{wt:[181,180,260]}))}}); assert.strictEqual(sent.length,0); assert.strictEqual(data.historyIndex,beforeConflictIndex); assert.strictEqual(data['historyChunk:0001'],beforeConflictChunk);
var duplicateIndex=data.historyIndex; handlers.appmessage({payload:{message:JSON.stringify(a)}}); assert.strictEqual(sent.pop().ack,7); assert.strictEqual(data.historyIndex,duplicateIndex);
var orphanKey='historyChunk:0123', orphanBytes=JSON.stringify({schemaVersion:1,records:[Object.assign({},a,{id:12})]}); data[orphanKey]=orphanBytes; data.historyIndex=JSON.stringify({schemaVersion:1,ids:['7'],nextChunk:1}); assert(sync.store(Object.assign({},a,{id:12}))); assert.strictEqual(data[orphanKey],orphanBytes); assert(sync.readIndex().ids.indexOf('12')>=0);
var corruptKey='historyChunk:0124', corruptBytes='{corrupt'; data[corruptKey]=corruptBytes; var validBytes=data['historyChunk:0001']; data.historyIndex='{bad'; assert(sync.store(Object.assign({},a,{id:13}))); assert.strictEqual(data[corruptKey],corruptBytes); assert.strictEqual(data['historyChunk:0001'],validBytes);
var repairBefore=data.historyIndex; failWrite=1; assert(!sync.store(Object.assign({},a,{id:14}))); failWrite=0; assert.strictEqual(data['historyChunk:0001'],validBytes); assert(sync.store(Object.assign({},a,{id:14})));
var conflictBefore=JSON.stringify(data); sent.length=0; handlers.appmessage({payload:{message:JSON.stringify(Object.assign({},a,{id:12,t:999}))}}); assert.strictEqual(sent.length,0); assert.strictEqual(JSON.stringify(data),conflictBefore);
sent.length=0; logs.length=0; handlers.appmessage({payload:{type:'calendar_request',id:41,year:2024,month:2}}); var cal=sent.pop(); assert.strictEqual(cal.calendar_id,41); assert.strictEqual(cal.calendar_year,2024); assert.strictEqual(cal.calendar_month,2); assert.strictEqual(cal.calendar_days,29); assert(logs.some(function(x){return x.indexOf('CALENDAR_REQUEST id=41 year=2024 month=2')===0;}));
sent.length=0; logs.length=0; handlers.appmessage({payload:{type:'progress_request',id:42,exercise:0,page:0}}); assert(sent.length>=1); sent.forEach(function(chunk){assert.strictEqual(chunk.progress_id,42);assert.strictEqual(chunk.progress_exercise,0);assert.strictEqual(chunk.progress_page,0);assert(chunk.progress_chunk_count>=1&&chunk.progress_point_count<=5);}); assert(logs.some(function(x){return x.indexOf('PROGRESS_REQUEST id=42 exercise=0 page=0')===0;}));
assert(logs.some(function(x){return x.indexOf('PROGRESS_SEND_OK id=42 chunk=0')===0;}));
// Pebble localStorage has get/set but may not expose enumeration.
global.localStorage={getItem:function(k){return data[k]===undefined?null:data[k];},setItem:function(k,v){data[k]=v;}};
sent.length=0; handlers.appmessage({payload:{type:'calendar_request',id:43,year:2024,month:1}}); assert.strictEqual(sent.pop().calendar_mask,0);
sent.length=0; handlers.appmessage({payload:{type:'progress_request',id:44,exercise:0,page:0}}); assert(sent.length>0&&sent[0].progress_id===44);
originalLog('sync js tests passed');
