#include <assert.h>
#include <string.h>
#include <stdio.h>
#include "../src/c/workout_completion.h"
#include "../src/c/persistence.h"
typedef struct { unsigned char b[32][256]; size_t n[32]; } Store;
static bool ex(uint32_t k,void*x){Store*s=x;return k<32&&s->n[k];} static int gs(uint32_t k,void*x){Store*s=x;return k<32?(int)s->n[k]:-1;}
static int rd(uint32_t k,void*p,size_t n,void*x){Store*s=x;if(k>=32||s->n[k]!=n)return-1;memcpy(p,s->b[k],n);return(int)n;} static int wr(uint32_t k,const void*p,size_t n,void*x){Store*s=x;if(k>=32||n>256)return-1;memcpy(s->b[k],p,n);s->n[k]=n;return(int)n;}
static const PersistenceAdapter A={ex,gs,rd,wr};
static void io(Store*s,PersistedState*v,int save){PersistedCoreState c={0};PersistedSyncState q={0};memcpy(&c,v,sizeof c);q.schema_version=v->schema_version;q.outbox=v->outbox;q.next_record_id=v->next_record_id;q.pending_record=v->pending_record;q.pending_valid=v->pending_valid;q.completion_blocked=v->completion_blocked;q.selected_reps=v->selected_reps;if(save)assert(persistence_save(&A,sizeof c,&c,sizeof q,&q,s)==PERSIST_OK);else{assert(persistence_load(&A,sizeof c,&c,sizeof q,&q,s,0)==PERSIST_OK);memset(v,0,sizeof*v);memcpy(v,&c,sizeof c);v->outbox=q.outbox;v->next_record_id=q.next_record_id;v->pending_record=q.pending_record;v->pending_valid=q.pending_valid;v->completion_blocked=q.completion_blocked;v->selected_reps=q.selected_reps;}}
static PersistedState start(WorkoutType w){PersistedState s={0};s.schema_version=WORKOUT_STORAGE_SCHEMA;s.active=1;s.active_workout=w;s.next_workout=w;s.exercise_index=2;s.set_index=w==WORKOUT_A?4:0;s.selected_reps=5;s.active_weights[0]=45;s.active_weights[1]=45;s.active_weights[2]=65;for(int e=0;e<3;e++)for(int n=0;n<5;n++)s.work_reps[e][n]=5;return s;}
static void workout(WorkoutType w,unsigned reps,const unsigned char ids[3]){Store st={0};PersistedState s=start(w);assert(workout_completion_attempt(&s,5,123)==COMPLETION_OK);assert(!s.active&&s.next_workout==(w==WORKOUT_A?WORKOUT_B:WORKOUT_A)&&s.outbox.count==1);assert(s.outbox.records[0].id&&s.outbox.records[0].workout==w&&s.outbox.records[0].rep_count==reps);for(int i=0;i<3;i++)assert(s.outbox.records[0].exercise_ids[i]==ids[i]);io(&st,&s,1);memset(&s,0,sizeof s);io(&st,&s,0);assert(!s.active&&s.outbox.count==1&&s.outbox.records[0].rep_count==reps);unsigned id=s.outbox.records[0].id;assert(workout_completion_handle_ack(&s,id)==SYNC_PUSH_IDENTICAL || workout_completion_handle_ack(&s,id)==SYNC_PUSH_ADDED);io(&st,&s,1);memset(&s,0,sizeof s);io(&st,&s,0);assert(s.outbox.count==0);assert(workout_completion_handle_ack(&s,id+1)==SYNC_PUSH_CONFLICT);}
int main(void){const unsigned char a[3]={0,1,2},b[3]={0,3,4};Store st={0};PersistedState lifecycle=start(WORKOUT_A);lifecycle.weights[0]=777;lifecycle.weights[1]=888;lifecycle.inventory_counts[0]=1;lifecycle.inventory_counts[1]=2;io(&st,&lifecycle,1);memset(&lifecycle,0,sizeof lifecycle);io(&st,&lifecycle,0);assert(lifecycle.weights[0]==777&&lifecycle.weights[1]==888&&lifecycle.inventory_counts[0]==1&&lifecycle.inventory_counts[1]==2);workout(WORKOUT_A,15,a);workout(WORKOUT_B,11,b);puts("Workout A/B production persistence and ACK reload passed");return 0;}
