var assert=require('assert'), data={}, handlers={}, sent=[], failKey=null, failWrite=0;
global.localStorage={get length(){return Object.keys(data).length;},key:function(i){return Object.keys(data)[i]||null;},getItem:function(k){return data[k]===undefined?null:data[k];},setItem:function(k,v){if(k===failKey||(--failWrite===0))throw Error('injected');data[k]=v;}};
global.Pebble={addEventListener:function(n,f){handlers[n]=f;},sendAppMessage:function(p){sent.push(p);}};
var sync=require('../src/pkjs/index.js');
var a={v:1,id:7,t:123,w:0,e:[0,1,2],wt:[180,180,260],r:Array(15).fill(5),c:1,d:0};
handlers.appmessage({payload:{message:JSON.stringify(a)}}); assert.strictEqual(sent.pop().ack,7); assert.strictEqual(sync.scanHistory().records['7'].id,7);
handlers.appmessage({payload:{message:JSON.stringify(a)}}); assert.strictEqual(sent.pop().ack,7);
var conflict=Object.assign({},a,{t:124}); sent.length=0; handlers.appmessage({payload:{message:JSON.stringify(conflict)}}); assert.strictEqual(sent.length,0);
handlers.appmessage({payload:{message:'bad'}}); assert.notStrictEqual(sent.pop().ack,7);
data.historyIndex='{bad'; var orphan=JSON.stringify({schemaVersion:1,records:[Object.assign({},a,{id:8})]}); data['historyChunk:0002']=orphan; assert(sync.store(Object.assign({},a,{id:8}))); assert.strictEqual(data['historyChunk:0002'],orphan);
failKey='historyChunk:0003'; sent.length=0; var indexBefore=data.historyIndex; handlers.appmessage({payload:{message:JSON.stringify(Object.assign({},a,{id:9}))}}); assert.strictEqual(sent.length,0); assert.strictEqual(data.historyIndex,indexBefore); failKey=null;
failWrite=1; assert(!sync.store(Object.assign({},a,{id:10}))); assert.strictEqual(data['historyChunk:0003'],undefined); failWrite=0;
failWrite=2; assert(!sync.store(Object.assign({},a,{id:10}))); failWrite=0; assert(sync.store(Object.assign({},a,{id:10})));
var corrupt='not-json'; data['historyChunk:0099']=corrupt; var beforeCorrupt=data['historyChunk:0099']; assert(sync.store(Object.assign({},a,{id:11}))); assert.strictEqual(data['historyChunk:0099'],beforeCorrupt);
['v','e','r'].forEach(function(k){var bad=Object.assign({},a); if(k==='v')bad.v=2; if(k==='e')bad.e=[0,3,4]; if(k==='r')bad.r=Array(14).fill(5); sent.length=0; handlers.appmessage({payload:{message:JSON.stringify(bad)}}); assert(sent.length===0||sent.pop().ack!==bad.id);});
var beforeConflictIndex=data.historyIndex, beforeConflictChunk=data['historyChunk:0001']; sent.length=0; handlers.appmessage({payload:{message:JSON.stringify(Object.assign({},a,{wt:[181,180,260]}))}}); assert.strictEqual(sent.length,0); assert.strictEqual(data.historyIndex,beforeConflictIndex); assert.strictEqual(data['historyChunk:0001'],beforeConflictChunk);
var duplicateIndex=data.historyIndex; handlers.appmessage({payload:{message:JSON.stringify(a)}}); assert.strictEqual(sent.pop().ack,7); assert.strictEqual(data.historyIndex,duplicateIndex);
console.log('sync js tests passed');
